### ISSUE TITLE
When I import a csv file, I find an error

### ISSUE THREAD

**Issue by TaiChiTiger** [yoyokits/BarChartRaceNet#6]
you did a great job, thank you for your job. When I import a csv file, I find an error like this:

Error: Exception thrown during processing
   at FFMpegCore.FFMpegArgumentProcessor.HandleException(Boolean throwOnError, Exception e, IReadOnlyList`1 errorData)
   at FFMpegCore.FFMpegArgumentProcessor.ProcessSynchronously(Boolean throwOnError, FFOptions ffMpegOptions)
   at BarChartRaceNet.Helpers.FFMpegHelper.Record(String outputFilePath, FrameworkElement element, Action`1 drawChartAction, Int32 frameCount, CancellationToken token) in C:\Data\GitHub\BarChartRaceNet\src\BarChartRaceNet\Helpers\FFMpegHelper.cs:line 69
   at BarChartRaceNet.ViewModels.ChartEditorViewModel.<>c__DisplayClass30_0.<<ExportChart>b__0>d.MoveNext() in C:\Data\GitHub\BarChartRaceNet\src\BarChartRaceNet\ViewModels\ChartEditorViewModel.cs:line 139

So, how to solve this problem?

**Comment by qwani** [comment]
yes he same here i think its  an error in inking mmpeg
